name: Package
packages:
  QuickTableViewController:
    url: file:./../../../QuickTableViewController
    revision: ${TRAVIS_COMMIT}
options:
  deploymentTarget:
    iOS: "13.0"
targets:
  App:
    type: application
    platform: iOS
    sources: Package
    settings:
      base:
        INFOPLIST_FILE: Package/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: "io.github.bcylin.QuickTableViewController.Package"
    dependencies:
      - package: QuickTableViewController
