name: Swift Package
on: [push, pull_request]

jobs:
  run-tests:
    name: Run tests
    runs-on: macOS-latest
    env:
      BUNDLE_PATH: vendor/bundle
      MINT_PATH: vendor/mint
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-ruby@v1.1.2
        with:
          ruby-version: '2.6.x'

      # Cache
      - name: Cache ${{ env.BUNDLE_PATH }}
        uses: actions/cache@v2.1.1
        with:
          path: ${{ env.BUNDLE_PATH }}
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-
      - name: Cache ${{ env.MINT_PATH }}
        uses: actions/cache@v2.1.1
        with:
          path: ${{ env.MINT_PATH }}
          key: ${{ runner.os }}-mint-${{ hashFiles('Mintfile') }}
          restore-keys: ${{ runner.os }}-mint-

      # Dependencies
      - name: Bundle install
        run: |
          gem install bundler -v `tail -1 Gemfile.lock`
          bundle config path ${{ env.BUNDLE_PATH }}
          bundle install --jobs 4 --retry 3
      - name: Mint bootstrap
        run: |
          brew list mint > /dev/null || brew install mint
          mint bootstrap

      # Build
      - run: |
          mint run yonaskolb/XcodeGen xcodegen generate --project Package --spec Package/Package.yml
      - run: |
          bundler exec fastlane swift_package
